### ISSUE TITLE
RangeError: Maximum call stack size exceeded with certain content

### ISSUE THREAD

**Issue by tveimo** [kontent-ai/kontent-delivery-node-parser#6]
### Brief bug description

I'm trying to use the node parser for url resolution, but am encountering RangeError in the striptags dependency used by it.

### Repro steps

Here's a gist: https://gist.github.com/tveimo/9ed80c181d80c449cc95dcf079c47cd6

run with ts-node --esm test.mts

### Test environment

We're using nuxt, typescript, node v18.12.1.

**Comment by Enngage** [comment]
Hi @tveimo,

There are 2 issues with your code - you should either use `linkHtml` or `linkUrl`, but not both. However, the main reason this ends up in infinite recursion exception is because you 'preserving' the `data-item-id="${linkId}"` which causes the parser to resolve it all over again. You should omit this in your resolved link. See working sample at https://stackblitz.com/edit/stackblitz-starters-txywxr?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js,package.json&title=node.new%20Starter

**Comment by tveimo** [comment]
Thanks!
